BEGIN;

CREATE TABLE metric (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    filter VARCHAR(1024) NOT NULL,
    step_seconds INTEGER NOT NULL,
    window_seconds INTEGER NOT NULL,
    ctime TIMESTAMP NOT NULL DEFAULT NOW()
) ENGINE INNODB;

COMMIT;
